mode: SEFD
root_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\Data\149

# RNN Model parameters
encoder_dim: 2
decoder_dim: 1
hidden_size: 64
encoder_layers: 1
decoder_layers: 1
dropout: 0

# DataModule parameters
encoder_input_length: 20
stride: 16
decoder_input_length: 1980
batch_size: 64
shuffle: True

# Normalization parameters
normalize: True
voltage_max: 4.2
voltage_min: 2.5
current_max: 1
current_min: -2.5