mode: SEFD
root_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\Data\2.0_temp_long_upsampled_20  
# RNN Model parameters
encoder_dim: 2
decoder_dim: 1
hidden_size: 32
encoder_layers: 1
decoder_layers: 1
dropout: 0

# DataModule parameters
encoder_input_length: 20
stride: 4 #16
decoder_input_length:  1920
batch_size: 256 # 64
shuffle: True

# Normalization parameters
normalize: True
voltage_max: 4.2
voltage_min: 2.5
current_max: 25 #2.5  #1
current_min: -10  # -1 #-2.5 # falsch skaliert bisher !?